<?php
/*
  Posee Carnet por “Posee Credencial,
  Fecha Vencimiento Carnet por “Fecha de Vencimiento Credencial”,
  Cta. Banco por “Cta. Banco”
*/
$leng =  array("rif" =>"Rut" ,
               "nit" =>"Nit" ,
               "juridico" =>"Juridico" ,
               "contribuyente" =>"Contribuyente" ,
               "nacional" =>"Nacional" ,
               "nacionalidad" =>"Nacionalidad" ,
               "estado_civil" =>"Estado Civil" ,
               "correo" =>"Correo" ,
               "region" =>"Regi&oacute;n",
               "pais" =>"Pais" ,
               "estado" =>"Provincia" ,
               "ciudad" =>"Comuna" ,
               "zona" =>"Zonas" ,
               "psic_fec" =>"Fecha Elaboración Examen Psicol&oacute;gico",
               "psic_desc" =>"Examen Psicol&oacute;gico" ,
               "psic_observ" =>"Observaci&oacute;n Exam. Pisicol&oacute;gico",
               "pol_fec" =>"Fecha de Chequeo Policial" ,
               "pol_desc" =>"Chequeo Policial" ,
               "pol_observ" =>"Observaci&oacute;n Chequeo Policial" ,
               "pre_emp_fec" =>"Fecha de Examen Preempleo" ,
               "pre_emp_desc" =>"Chequeo Examen Preempleo" ,
               "pre_emp_observ" =>"Observaci&oacute;n Chequeo Examen Preempleo" ,
               
               "aprobado" =>"Aprobado" ,
               "reprobado" =>"Reprobado" ,
               "condiccional" =>"Condiccional",
               "indefinido" =>"Indefinido",
               "F" =>"Femenimo",
               "M"=>"Masculino",

               "aceptado" =>"Aceptado",
               "rechazado" =>"Rechazado",
               "pendiente" =>"Pendinte",

               "ci" => "Rut",
               "trabajador" =>"Trabajador",
               "trab" =>"Trab",
               "nomina" => "Nomina",
               "concepto"=> "Concepto",
               "rol" =>"Agrupaci&oacute;n",
               "contrato" => "Contrato",
               "contratacion" => "XX Contrataci&oacute;n",
               "ficha" => "Ficha",
               "cliente" => "Empresa",
               "ubicacion" => "Ubicaci&oacute;n",
               "horario" => "Horas",
               "turno" => "Turnos",
               "rotacion" => "Rotacion De Turnos ",
               "dia_habil" => "D&iacute;a Habil ",
               "planificacion" => " Planificaci&oacute;n ",
             );
 ?>
