<?php
$leng =  array("rif" =>"XX Rif" ,
               "nit" =>"XX Nit" ,
               "juridico" =>"XX Juridico" ,
               "contribuyente" =>"XX Contribuyente" ,
               "nacional" =>"XX nacional" ,
               "nacionalidad" =>"XX Nacionalidad" ,
               "estado_civil" =>"XX Estado Civil" ,
               "correo" =>"XX Correo" ,
               "region" =>"XX Region",
               "pais" =>"XX Pais" ,
               "estado" =>"XX Estado" ,
               "ciudad" =>"XX Ciudad" ,
               "zona" =>"Zonas" ,
               "psic_fec" =>"XX Fecha Elaboración Examen Psicológico",
               "psic_desc" =>"XX Examen Psicológico" ,
               "psic_observ" =>"XX Observación Exam. Pisicológico",
               "pol_fec" =>"XX Fecha de Chequeo Policial" ,
               "pol_desc" =>"XX Chequeo Policial" ,
               "pol_observ" =>"XX Observación Chequeo Policial" ,
               "pre_emp_fec" =>"XX Fecha de Examen Preempleo" ,
               "pre_emp_desc" =>"XX Chequeo Examen Preempleo" ,
               "pre_emp_observ" =>"XX Observaci&oacute;n Chequeo Examen Preempleo" ,

               "aprobado" =>"XX Aprobado" ,
               "reprobado" =>"XXReprobado" ,
               "condiccional" =>"XX Condiccional",
               "indefinido" =>"XX Indefinido",

               "F" =>"XX Femenimo",
               "M"=>"XX Masculino",

               "aceptado" =>"XX Aceptado",
               "rechazado" =>"XX Rechazado",
               "pendiente" =>"XX Pendinte",

              "ci" => "C&eacute;dula íí",
               "trabajador" =>"XX Trabajador",
               "trab" =>"XX Trab",
               "nomina" => "Nomina X",
               "concepto"=> "Concepto X",
               "rol" =>"X Agrupación",
               "contrato" => "XX Contrato",
              "contratacion" => "XX Contrataci&oacute;n",
               "ficha" => "XX Ficha",
               "cliente" => "Empresa",
               "ubicacion" => "Localidad ubicacion",
               "horario" => "Horas",
               "turno" => "Turnos",
               "rotacion" => "Rotacion De Turnos ",
               "dia_habil" => "D&iacute;a Habil ",
               "planificacion" => " Planificaci&oacute;n XX ",

             );
 ?>
